Revert "enable UT tests for xpu"
This reverts commit 7a365bb8bd453819d6037fbd1dc792b6976bcc0a.

diff --git a/.github/workflows/pr-test-xpu.yml b/.github/workflows/pr-test-xpu.yml
--- a/.github/workflows/pr-test-xpu.yml
+++ b/.github/workflows/pr-test-xpu.yml
@@ -10,7 +10,32 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  rebase-pr-branch:
+    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
+    runs-on: pvc-1100
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.ref }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Rebase PR branch onto target branch
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+
+          git fetch origin ${{ github.base_ref }} --depth=1
+
+          git rebase origin/${{ github.base_ref }} || {
+            echo "Rebase failed, likely due to conflicts. Please rebase manually."
+            exit 1
+          }
+
+          git push origin HEAD:${{ github.event.pull_request.head.ref }} --force
   build-and-test:
+    needs: rebase-pr-branch
     if: (github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request') &&
       github.event.pull_request.draft == false
     runs-on: pvc-1100
@@ -45,19 +70,13 @@ jobs:
           docker exec ci_sglang_xpu /miniforge3/envs/py310/bin/python3 -m pip install --upgrade pip
           docker exec ci_sglang_xpu /miniforge3/envs/py310/bin/python3 -m pip install pytest expecttest ray
 
-      - name: Run Sglang Kernel Cases
+      - name: Run UT Cases
         timeout-minutes: 20
         run: |
           docker exec -w /root/sglang ci_sglang_xpu \
             /bin/bash -c "cd /root/sglang/sgl-kernel/tests && source /opt/intel/oneapi/setvars.sh && /miniforge3/envs/py310/bin/python3 -m pytest -v -s test_awq_dequant.py"
 
-      - name: Run Sglang UT Cases
-        timeout-minutes: 60
-        run: |
-          docker exec -w /root/sglang ci_sglang_xpu \
-            /bin/bash -c "cd /root/sglang/tests/srt && source /opt/intel/oneapi/setvars.sh && /miniforge3/envs/py310/bin/python3 -m run_suite.py --suite per-commit-xpu-intel"
-
-      - name: Run E2E Bfloat16 tests
+      - name: Run standard tests
         timeout-minutes: 20
         run: |
           docker exec -w /root/sglang ci_sglang_xpu \
@@ -70,7 +89,7 @@ jobs:
             --mem-fraction-static 0.3 \
             --device xpu"
 
-      - name: Run E2E Qunatization tests
+      - name: Run Qunatization tests
         timeout-minutes: 20
         run: |
           docker exec -w /root/sglang ci_sglang_xpu \
